#!/usr/bin/env bash

# goofy hlwm conf

hc() {
    herbstclient "$@"
}

# I have no idea
hc emit_hook reload

#hsetroot -fill ~/.wallpapers/wallhaven-eox27o.jpg
hsetroot -solid '#758a8b'
#nitrogen --restore

# uh, self explanatory
hc keyunbind --all

# keybindings
Mod=Mod4

hc keybind $Mod-Control-q quit
hc keybind $Mod-Control-r reload

# essentials
hc keybind $Mod-q close
hc keybind $Mod-Return spawn "wezterm"
hc keybind $Mod-w spawn "chromium"
hc keybind $Mod-e spawn "pcmanfm"
hc keybind $Mod-Control-c spawn "flameshot gui &"

# tags
tag_names=( "1" "2" "3" "4" "5" )
tag_keys=( {1..5} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if [ -n "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-d set_attr clients.focus.decorated toggle
hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
hc keybind $Mod-Control-m jumpto last-minimized
hc keybind $Mod-p pseudotile toggle
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# basically alt tab
hc keybind $Mod-Tab cycle_all +1

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border-width 0
hc set frame_gap 0
hc set frame_border_active_color '#00000000'
hc set frame_border_normal_color '#00000000'
hc set frame_bg_normal_color '#00000000'
hc set frame_bg_active_color '#00000000'

hc attr theme.title_height 40
hc attr theme.title_when always
hc attr theme.title_font 'JetBrainsMono Nerd Font:pixelsize=12'
hc attr theme.title_depth -60
hc attr theme.active.color '#fa8072'
hc attr theme.title_color '#fa8072'
hc attr theme.normal.color '#fa8072'
hc attr theme.urgent.color '#fa8072'
hc attr theme.normal.title_color '#fa8072'

# borders
hc attr theme.border_width 0
hc attr theme.background_color '#181818'

hc attr theme.floating.window_border_width 10

hc set window_gap 12

# rules
hc unrule -F
hc rule focus=on
hc rule floatplacement=smart
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=off
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule fixedsize floating=on

hc set tree_style '╾│ ├└╼─┐'

hc unlock

# autostart
pkill sxhkd
pkill picom
pkill eww
pkill nm-applet
pkill discord
sxhkd &
picom -b &
eww daemon &
eww open main
nm-applet &
discord &
